### ISSUE TITLE
[TRACKING] UART Hardware Testing Support

### ISSUE THREAD

**Issue by MrKevinWeiss** [MrKevinWeiss/Testing#1]
# BPT Firmware

- [ ] Add UART configuration functionality to the BPT (blue pill tester)
     - [ ] add app_uart.c/h
     - [ ] modify app.c/h
     - [ ] modify app_typedef.h
     - [ ] modify serial_com.c/h

# Qualification Test for BPT
- [ ] Add qualification test for UART functionality for BPT
     - [ ] design procedure to qualify UART on BPT
     - [ ] add test script for automated testing
     - [ ] add documentation for test results and manual testing

# Interface for BPT
- [ ] Modify interface for BPT to support UART configuration
     - [ ] modify cmd_list.py (maybe rename to bpt_if.py)

# RIOT UART Test
- [ ] Modify RIOT shell interface to run extensible UART tests against API
     - [ ] modify tests/periph_uart/main.c

# RIOT UART Test Interface
- [ ] Add interface to RIOT periph_uart test to make writing tests easier
     - [ ] add periph_uart_if.py

# Automated Test
- [ ] Add test using interfaces to the test suite

#Verification of Automated Test
- [ ] Ensure test functions on at least one DUT (device under test)
