### ISSUE TITLE
bpt: TODO I2C improvments

### ISSUE THREAD

**Issue by MrKevinWeiss** [MrKevinWeiss/Testing#36]
- [ ] Add 16 bit register support
- [ ] Add last read/write count
- [ ] Support nack injection
- [ ] 10 bit address support
- [ ] Improve portability
- [ ] Update commenting and documentation
- [ ] Remove blocking clk_stretch
- [ ] Add status register
- [ ] Add repeated start read sensing
- [ ] Add clock speed estimation
- [ ] Add error/status reg

**Comment by MrKevinWeiss** [comment]
moving to https://github.com/riot-appstore/PHiLIP/issues/3
