### ISSUE TITLE
code_gen: TODO tracking

### ISSUE THREAD

**Issue by MrKevinWeiss** [MrKevinWeiss/Testing#5]
- [x] Add an output of the register list from the code generator
- [x] Add information on slave ID to the documentation
- [x] Add ability to make defaults
- [x] Add ability to set register access
- [x] Support mem map specifier
- [x] Add bit access for mem_map
- [ ] Add name compress flag
- [ ] Add web interface
- [x] Add output for python interface
- [x] Add generated python test
- [ ] Update documentation

**Comment by MrKevinWeiss** [comment]
close due to:
https://github.com/riot-appstore/memory_map_manager/issues/1
https://github.com/riot-appstore/memory_map_manager/issues/2
